"""Improving retrieval with LLM-generated query rephrasings.

Some retrieval misses aren't a retrieval bug — they're a vocabulary
mismatch between how a question is phrased and how the evidence is
worded (verified directly against this course's own sample passages: "are
consumer price increases cooling off?" misses the inflation passage
entirely, while "is inflation slowing down?" finds it immediately). Query
expansion asks the LLM for alternative phrasings, retrieves for each, and
merges the results — the same injected `generate` pattern as Week 7/10.
"""

from __future__ import annotations

import json
from collections.abc import Callable

from chromadb.api.models.Collection import Collection
from pydantic import BaseModel

from ai_finance_course.vector_store import query_collection


class QueryExpansion(BaseModel):
    """Alternative phrasings of a query, generated by an LLM."""

    rephrasings: list[str]


def build_expansion_prompt(query: str) -> str:
    """Build a role/task/constraints/output-format prompt (Week 6's structure).

    No EVIDENCE section here — unlike Week 10's grounded prompt, expanding
    a query doesn't need retrieved evidence, only the question itself.
    """
    return f"""ROLE: You are a search-query specialist who rewrites financial research \
questions to improve retrieval from a semantic search index.

TASK: Write 2 alternative phrasings of the question below that preserve its exact \
meaning but use different wording, so a semantic search index is more likely to find \
relevant passages phrased differently from the original question.

QUESTION: {query}

CONSTRAINTS:
- Do not change what is being asked, only how it's phrased.
- Each rephrasing must be a complete question or statement on its own.
- Prefer spelling out company names in full rather than using ticker symbols \
(e.g. "Microsoft" rather than "MSFT") — full names tend to match filing text better.

OUTPUT FORMAT: Return ONLY valid JSON, no other text, matching this shape:
{{"rephrasings": ["...", "..."]}}"""


def _extract_json(text: str) -> str:
    """Strip a ```json fence around the response, if the model added one."""
    stripped = text.strip()
    if stripped.startswith("```"):
        stripped = stripped.strip("`")
        stripped = stripped.removeprefix("json").strip()
    return stripped


def expand_query(query: str, generate: Callable[[str], str]) -> list[str]:
    """Generate alternative phrasings of a query.

    Args:
        query: The original question.
        generate: A function that takes a prompt and returns the LLM's raw
            text response. Injected so this function never calls a
            provider's API directly.

    Returns:
        The original query, followed by the LLM's rephrasings, in order —
        the original is always included so expansion can only add
        retrieval coverage, never remove it.

    Raises:
        pydantic.ValidationError: If the LLM's response doesn't match the
            expected shape (a subclass of ValueError — Week 7 §3.3).
    """
    prompt = build_expansion_prompt(query)
    raw_response = generate(prompt)
    parsed = json.loads(_extract_json(raw_response))
    expansion = QueryExpansion(**parsed)
    return [query] + expansion.rephrasings


def retrieve_with_expansion(
    collection: Collection,
    query: str,
    n_results: int = 3,
    *,
    generate: Callable[[str], str],
    where: dict | None = None,
) -> list[dict]:
    """Retrieve using the original query plus LLM-generated rephrasings, merged.

    Args:
        collection: A ChromaDB collection from vector_store.get_or_create_collection.
        query: The original question.
        n_results: How many results to return, after merging every variant's results.
        generate: Passed to expand_query — keyword-only so this function's
            (collection, query, n_results) signature matches query_collection's,
            letting retrieval_eval.hit_rate call either one the same way.
        where: Optional metadata filter, passed through to every variant's query.

    Returns:
        Up to n_results {"text", "metadata", "distance"} dicts, deduplicated
        by chunk text and sorted by distance (lowest/most-similar first) —
        the best match across every phrasing, not just the original.
    """
    queries = expand_query(query, generate)

    best_by_text: dict[str, dict] = {}
    for variant in queries:
        for result in query_collection(collection, variant, n_results=n_results, where=where):
            existing = best_by_text.get(result["text"])
            if existing is None or result["distance"] < existing["distance"]:
                best_by_text[result["text"]] = result

    return sorted(best_by_text.values(), key=lambda r: r["distance"])[:n_results]
